import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'

import LayoutContentWrapper from '@/components/LayoutContentWrapper'
import MainNavigation from '@/components/MainNavigation'
import { TRPCProvider } from '@/lib/trpc/TRPCProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <TRPCProvider>
          <MainNavigation />
          <LayoutContentWrapper>
            <main>{children}</main>
          </LayoutContentWrapper>
          <Toaster />
        </TRPCProvider>
      </body>
    </html>
  )
}
